name: .NET Core

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build src/GPS.Collections.sln --configuration Debug --no-restore
    - name: Test
      run: dotnet test src/GPS.Collections.sln --no-restore --verbosity normal
       
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Publish NuGet
       uses: brandedoutcast/publish-nuget@v2.5.5     
       with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: ./src/GPS.Collections/GPS.Collections.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY:  ${{ secrets.NUGET_KEY }}
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true
      
